-- Development-only regression examples. This file is not loaded by the addon.
return {
    { message = "<Example Guild> is recruiting active players! Join us and whisper for invite", blocked = true, module = "GuildRecruitment" },
    { message = "Any casual guilds recruiting healers?", blocked = false },
    { message = "<Azeroth's Adventurers> Fully independent Guild looking for more Members. Come be part of the Journey. New Players and Veterans alike are welcome!", blocked = true, module = "GuildRecruitment" },
    { message = "Tired of lame-os? come chill with some <Dirty Rotten Imbeciles> Progress through PvE with us, and through PvP with us, High risk, Mythics, and make some chill friends and memories. ACTIVE DISCORD AND CHAT", blocked = true, module = "GuildRecruitment" },
    { message = "Any guild looking for more members?", blocked = false },
    { message = "WTS 500 DP, good rate, whisper me", blocked = true, module = "CurrencySpam" },
    { message = "WTB |cffffffff|Hitem:975001:0:0:0:0:0:0:0|h[Bazaar Token]|h|r 45s each whisper me", blocked = true, module = "CurrencySpam" },
    { message = "WTS 100DP + 1000 Bazaar for 2200g", blocked = true, module = "CurrencySpam" },
    { message = "wtb 2800 baz tokens", blocked = true, module = "CurrencySpam" },
    { message = "Did they change the DP store?", blocked = false },
    { message = "LIVE NOW twitch.tv/example come hang out", blocked = true, module = "StreamAdvertising" },
    { message = "Did you watch that Twitch streamer yesterday?", blocked = false },
    { message = "guildimize oyuncu arıyoruz", blocked = true, module = "NonEnglish" },
    { message = "tražimo igrače za večeras", blocked = true, module = "NonEnglish" },
    { message = "A Cruzada Escarlate está de portas abertas para você! Participe de raids, eventos de RP, batalhas de PvP e muito mais. Todos são bem-vindos, veteranos ou novatos. Venha fazer parte da nossa irmandade!", blocked = true, module = "NonEnglish" },
    { message = "GUILD MAS ESPAÑOLA QUE FRANCO WHISP NO LATAM NO PANCHO", blocked = true, module = "NonEnglish" },
    { message = "selam", blocked = false },
    { message = "LFM tank and healer for BRD", blocked = false },
}
