-- Development-only regression examples. This file is not loaded by the addon.
return {
    { message = "<Example Guild> is recruiting active players! Join us and whisper for invite", blocked = true, module = "GuildRecruitment" },
    { message = "Any casual guilds recruiting healers?", blocked = false },
    { message = "<Azeroth's Adventurers> Fully independent Guild looking for more Members. Come be part of the Journey. New Players and Veterans alike are welcome!", blocked = true, module = "GuildRecruitment" },
    { message = "Tired of lame-os? come chill with some <Dirty Rotten Imbeciles> Progress through PvE with us, and through PvP with us, High risk, Mythics, and make some chill friends and memories. ACTIVE DISCORD AND CHAT", blocked = true, module = "GuildRecruitment" },
    { message = "Any guild looking for more members?", blocked = false },
    { message = "WTS 500 DP, good rate, whisper me", blocked = true, module = "CurrencySpam" },
    { message = "WTB |cffffffff|Hitem:975001:0:0:0:0:0:0:0|h[Bazaar Token]|h|r 45s each whisper me", blocked = true, module = "CurrencySpam" },
    { message = "WTS 100DP + 1000 Bazaar for 2200g", blocked = true, module = "CurrencySpam" },
    { message = "wtb 2800 baz tokens", blocked = true, module = "CurrencySpam" },
    { message = "WTS [Jaina's Dimensional Pocket] for 8.5g Many in stock! PST!!!", blocked = false },
    { message = "Did they change the DP store?", blocked = false },
    { message = "LIVE NOW twitch.tv/example come hang out", blocked = true, module = "StreamAdvertising" },
    { message = "Did you watch that Twitch streamer yesterday?", blocked = false },
    { message = "guildimize oyuncu arıyoruz", blocked = true, module = "NonEnglish" },
    { message = "tražimo igrače za večeras", blocked = true, module = "NonEnglish" },
    { message = "A Cruzada Escarlate está de portas abertas para você! Participe de raids, eventos de RP, batalhas de PvP e muito mais. Todos são bem-vindos, veteranos ou novatos. Venha fazer parte da nossa irmandade!", blocked = true, module = "NonEnglish" },
    { message = "GUILD MAS ESPAÑOLA QUE FRANCO WHISP NO LATAM NO PANCHO", blocked = true, module = "NonEnglish" },
    { message = "Si quieren GUILD LATAM FULL PVP susurrenme!!!", blocked = true, module = "NonEnglish" },
    { message = "MYT GUILD HABLA HISPANA LATINA. ENFOCADA EN EL CONTENIDO PVE RECLUTAMOS GENTE PARA COMPLETAR EL CONTENIDO DE CLASSIC. AMBIENTE CHILL", blocked = true, module = "NonEnglish" },
    { message = "Doom recrute des HORDEUX ouvert à tout type de joueur pour la HORDE!!!", blocked = true, module = "NonEnglish" },
    { message = "[Styx] Polska gildia, ktora stale sie rozrasta, zaprasza do wspolnej rozgrywki! Leveling, dungi, BG, a w przyszlosci takze raidy, na ktore bardzo czekamy. Tryhard, newbie czy weekendowym gracz? znajdzie sie u nas miejsce dla Ciebie.", blocked = true, module = "NonEnglish" },
    { message = "<Kulový blesk> CZ/SK guilda nabírá! Raidy, dungeony, chill atmosféra a pohodová parta. Novácci i zkušení hráci vítáni — každý má místo! Whisper pro invite/info.", blocked = true, module = "NonEnglish" },
    { message = "<cleanse> Multiple First Kills auf BB sucht starke, langfristige Spieler mit Anspruch! Discord: https://discord.gg/fqYRPnfjxW oder /w me", blocked = true, module = "NonEnglish" },
    { message = "hola gente", blocked = false },
    { message = "bonjour", blocked = false },
    { message = "selam", blocked = false },
    { message = "Polska", blocked = false },
    { message = "sucht", blocked = false },
    { message = "CZ/SK", blocked = false },
    { message = "LFM tank and healer for BRD", blocked = false },

    -- Channel Hygiene scenarios require channel/sender state in the test harness.
    { message = "WTS Arcane Crystal 20g", sender = "Seller", channel = "General", blocked = true, module = "ChannelHygiene" },
    { message = "WTS Arcane Crystal 20g", sender = "Seller", channel = "Trade", blocked = false },
    { message = "LFM tank for BRD", sender = "Leader", channel = "Trade", blocked = true, module = "ChannelHygiene" },
    { message = "LFM tank for BRD", sender = "Leader", channel = "Ascension", blocked = false },
    { message = "LFM tank for BRD", sender = "Leader", channel = "Newcomers", blocked = true, module = "ChannelHygiene", repeated = true },
}
