-- Development-only regression examples. This file is not loaded by the addon.
return {
    { message = "<Example Guild> is recruiting active players! Join us and whisper for invite", blocked = true, module = "GuildRecruitment" },
    { message = "Any casual guilds recruiting healers?", blocked = false },
    { message = "<Azeroth's Adventurers> Fully independent Guild looking for more Members. Come be part of the Journey. New Players and Veterans alike are welcome!", blocked = true, module = "GuildRecruitment" },
    { message = "Tired of lame-os? come chill with some <Dirty Rotten Imbeciles> Progress through PvE with us, and through PvP with us, High risk, Mythics, and make some chill friends and memories. ACTIVE DISCORD AND CHAT", blocked = true, module = "GuildRecruitment" },
    { message = "<Edgy Name Here> Ascended BB Raiding (Still Goin 2x/wk) M/W 8:45p-11:45p CST Looking for more social adds who still have interest in BB. discord.gg/enh Chill dad guild, leave the drama with yo mama.", blocked = true, module = "GuildRecruitment" },
    { message = "<Exalted with KFC> is a newly formed, EU based guild. Chill community of players who recently got into CoA and are looking to explore end game content, including dungeons and raids. Everyone is welcome! Pm for more info!", blocked = true, module = "GuildRecruitment" },
    { message = "I can't stop <Jorkin My Hog> We are a PvP/Leveling focused guild. Come hangout, share the experience and make some new homies. Dwarves highly encouraged.", blocked = true, module = "GuildRecruitment" },
    { message = "<Network Error> guild is recruting! Seeking players for leveling, end game raids and structured pvp. Active, experienced and mature leadership - We loves healers, chronomancers, tinkers, support specs and witch hunters, whisper for more info or an invite!", blocked = true, module = "GuildRecruitment" },
    { message = "Any guild looking for more members?", blocked = false },
    { message = "Looking for more social players for BRD?", blocked = false },
    { message = "Come hang out for a dungeon?", blocked = false },
    { message = "Seeking players for BRD?", blocked = false },
    { message = "Is <Network Error> guild recruting?", blocked = false },
    { message = "WTS 500 DP, good rate, whisper me", blocked = true, module = "CurrencySpam" },
    { message = "WTB |cffffffff|Hitem:975001:0:0:0:0:0:0:0|h[Bazaar Token]|h|r 45s each whisper me", blocked = true, module = "CurrencySpam" },
    { message = "WTS 100DP + 1000 Bazaar for 2200g", blocked = true, module = "CurrencySpam" },
    { message = "wtb 2800 baz tokens", blocked = true, module = "CurrencySpam" },
    { message = "WTS [Jaina's Dimensional Pocket] for 8.5g Many in stock! PST!!!", blocked = false },
    { message = "Did they change the DP store?", blocked = false },
    { message = "LIVE NOW twitch.tv/example come hang out", blocked = true, module = "StreamAdvertising" },
    { message = "Did you watch that Twitch streamer yesterday?", blocked = false },
    { message = "guildimize oyuncu arıyoruz", blocked = true, module = "NonEnglish" },
    { message = "tražimo igrače za večeras", blocked = true, module = "NonEnglish" },
    { message = "A Cruzada Escarlate está de portas abertas para você! Participe de raids, eventos de RP, batalhas de PvP e muito mais. Todos são bem-vindos, veteranos ou novatos. Venha fazer parte da nossa irmandade!", blocked = true, module = "NonEnglish" },
    { message = "GUILD MAS ESPAÑOLA QUE FRANCO WHISP NO LATAM NO PANCHO", blocked = true, module = "NonEnglish" },
    { message = "Si quieren GUILD LATAM FULL PVP susurrenme!!!", blocked = true, module = "NonEnglish" },
    { message = "MYT GUILD HABLA HISPANA LATINA. ENFOCADA EN EL CONTENIDO PVE RECLUTAMOS GENTE PARA COMPLETAR EL CONTENIDO DE CLASSIC. AMBIENTE CHILL", blocked = true, module = "NonEnglish" },
    { message = "Doom recrute des HORDEUX ouvert à tout type de joueur pour la HORDE!!!", blocked = true, module = "NonEnglish" },
    { message = "[Styx] Polska gildia, ktora stale sie rozrasta, zaprasza do wspolnej rozgrywki! Leveling, dungi, BG, a w przyszlosci takze raidy, na ktore bardzo czekamy. Tryhard, newbie czy weekendowym gracz? znajdzie sie u nas miejsce dla Ciebie.", blocked = true, module = "NonEnglish" },
    { message = "<Kulový blesk> CZ/SK guilda nabírá! Raidy, dungeony, chill atmosféra a pohodová parta. Novácci i zkušení hráci vítáni — každý má místo! Whisper pro invite/info.", blocked = true, module = "NonEnglish" },
    { message = "<cleanse> Multiple First Kills auf BB sucht starke, langfristige Spieler mit Anspruch! Discord: https://discord.gg/fqYRPnfjxW oder /w me", blocked = true, module = "NonEnglish" },
    { message = "<EXCEED {DE}> DEUTSCHE RAIDGILDE sucht Raidmember für den kommenden Ascended Content. Alle Raids auf Bronzebeard in Ascended Clear. Meldet euch wenn ihr bock auf entspanntes aber erfolgreiches Raiden habt. Auch Ascension Newcommer willkommen", blocked = true, module = "NonEnglish" },
    { message = "REKRUTUJEMY guildia GUROM POLSKA zaczyna nowa przygode MAKE WOW GRREAT AGAIN na ascension, SOCJALNA GUILDIA co chcesz to masz ziemniaczki, tetniaczki dla Ciebie, System DKP, new player ENYOJABLE. MIN MAXing to Twoje drugie imie? GENIALNIE to idealne miejsce", blocked = true, module = "NonEnglish" },
    { message = "Welkom In de Herberg een Nederlands/Belgische Guild ook wel bekend van Bronzebeard maakt hier een tweede thuis voor nu lekker levelen en we zijn al bezig met world bosses elke woensdag schuif aan en drink een biertje met ons!", blocked = true, module = "NonEnglish" },
    { message = "hola gente", blocked = false },
    { message = "bonjour", blocked = false },
    { message = "selam", blocked = false },
    { message = "Polska", blocked = false },
    { message = "Rekrutujemy", blocked = false },
    { message = "Welkom", blocked = false },
    { message = "Nederlands", blocked = false },
    { message = "sucht", blocked = false },
    { message = "CZ/SK", blocked = false },
    { message = "Raidmember", blocked = false },
    { message = "Willkommen", blocked = false },
    { message = "LFM tank and healer for BRD", blocked = false },

    -- Channel Hygiene scenarios require channel/sender state in the test harness.
    { message = "WTS Arcane Crystal 20g", sender = "Seller", channel = "General", blocked = true, module = "ChannelHygiene" },
    { message = "WTS Arcane Crystal 20g", sender = "Seller", channel = "Trade", blocked = false },
    { message = "LFM tank for BRD", sender = "Leader", channel = "Trade", blocked = true, module = "ChannelHygiene" },
    { message = "LFM tank for BRD", sender = "Leader", channel = "Ascension", blocked = false },
    { message = "LFM tank for BRD", sender = "Leader", channel = "Newcomers", blocked = true, module = "ChannelHygiene", repeated = true },
}
